name: Continuous Integration

on:
 push:
  branches:
   - main
 workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-latest
  env:
   docker_username: ${{secrets.DOCKERUSERNAME}}
   docker_password: ${{secrets.DOCKERPASSWORD}}
   docker_image: karthikamn/webapp:v1.0
  steps:
   - name: Checkout
     uses: actions/checkout@v4.2.2
   - name: Docker login
     uses: docker/login-action@v2
     with:
      username: ${{env.docker_username}}
      password: ${{env.docker_password}}
   - name: Build Docker image
     run: |
      docker build -t ${{env. docker_image}}:${{github.sha}} .
      docker tag ${{env.docker_image}}:${{github.sha}} ${{env.docker_image}}:latest
